let {API_URL, SOCKET_URL, PROXY_API_URL, REDIRECT_URI, CLIENT_ID} = window.M;

export default {
  API_URL: API_URL,
  SOCKET_URL: SOCKET_URL,
  PROXY_API_URL: PROXY_API_URL,
  CLIENT_ID: CLIENT_ID,
  REDIRECT_URI: REDIRECT_URI,
  INSTAGRAM_URL: 'https://api.instagram.com/v1'
};
